### ISSUE TITLE
Add .net Framework support

### ISSUE THREAD

**Issue by mrlyceist** [Wissance/Authorization#11]
Hello!
We want to use your library for our legacy project, but it seems that it targets only core/standard versions of dotnet. Could you please add the support for .Net Framework 4.7?

**Comment by EvilLord666** [comment]
I'll check and will add support for classical .net  framework asap

**Comment by EvilLord666** [comment]
Done, created Release 1.1.1 and updated nuget package (https://www.nuget.org/packages/Wissance.Authorization/) with same version. @mrlyceist,  please check

**Comment by mrlyceist** [comment]
Looks like it works, thank you so much!
